defmodule Reverb.Promotion do
  @moduledoc """
  Coordinator-owned promotion policy for validated task changes.
  """

  alias Reverb.{Git, Tasks}
  alias Reverb.Tasks.Task

  @type outcome :: %{
          action: :mark_stable | :mark_awaiting_approval,
          done_note: String.t(),
          pr_url: String.t() | nil,
          remote_ref: String.t() | nil,
          remote_status: atom()
        }

  @spec mode() :: :local_only | :manual | :auto
  def mode do
    config = Application.get_env(:reverb, Reverb.Git, [])

    cond do
      not remote_enabled?(config) -> :local_only
      Keyword.get(config, :auto_promote, true) -> :auto
      true -> :manual
    end
  end

  @spec prepare(%Task{}) :: {:ok, outcome()} | {:error, term()}
  def prepare(%Task{} = task) do
    case mode() do
      :local_only ->
        {:ok,
         %{
           action: :mark_stable,
           done_note: "Validated locally",
           pr_url: nil,
           remote_ref: nil,
           remote_status: :local_only
         }}

      :manual ->
        {:ok,
         %{
           action: :mark_awaiting_approval,
           done_note: "Validated locally and awaiting approval for push/PR",
           pr_url: nil,
           remote_ref: task.branch_name,
           remote_status: :push_pending
         }}

      :auto ->
        publish(task)
    end
  end

  @spec approve(%Task{}) :: {:ok, outcome()} | {:error, term()}
  def approve(%Task{} = task) do
    if task.state == :awaiting_approval do
      publish(task)
    else
      {:error, {:invalid_transition, task.state, :stable}}
    end
  end

  defp publish(%Task{} = task) do
    with {:ok, task} <- Tasks.mark_remote_status(task, :push_pending),
         :ok <- Git.push_branch(task.branch_name),
         {:ok, task} <- Tasks.mark_remote_status(task, :pushed),
         {:ok, pr_url} <- Git.open_or_update_pr(task.branch_name, pr_title(task), pr_body(task)) do
      {:ok,
       %{
         action: :mark_stable,
         done_note: "Validated locally and opened PR: #{pr_url}",
         pr_url: pr_url,
         remote_ref: task.branch_name,
         remote_status: :pr_opened
       }}
    end
  end

  defp remote_enabled?(config) do
    Keyword.get(config, :remote_enabled, false) and Keyword.get(config, :push_enabled, false)
  end

  defp pr_title(task) do
    "reverb: #{String.slice(task.body, 0, 72)}"
  end

  defp pr_body(task) do
    """
    Generated by Reverb.

    Task ID: #{task.id}
    Subject: #{task.subject || "n/a"}
    """
  end
end
